services:
  - type: web
    name: client
    runtime: node
    plan: free
    autoDeploy: false
    buildCommand: npm install && npm run build
    startCommand: npm start

  - type: web
    name: server
    runtime: node
    plan: free
    autoDeploy: false
    buildCommand: npm install
    startCommand: node server.js

  - type: web
    name: database
    runtime: mongodb
    plan: free
    autoDeploy: false
